// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package common

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD06268a7DecodeECCommon(in *jlexer.Lexer, out *Packet) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SourceIP":
			out.SourceIP = string(in.String())
		case "DestinationIP":
			out.DestinationIP = string(in.String())
		case "ID":
			out.ID = string(in.String())
		case "Response":
			out.Response = string(in.String())
		case "Content":
			if in.IsNull() {
				in.Skip()
				out.Content = nil
			} else {
				out.Content = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD06268a7EncodeECCommon(out *jwriter.Writer, in Packet) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SourceIP\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceIP))
	}
	{
		const prefix string = ",\"DestinationIP\":"
		out.RawString(prefix)
		out.String(string(in.DestinationIP))
	}
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"Response\":"
		out.RawString(prefix)
		out.String(string(in.Response))
	}
	{
		const prefix string = ",\"Content\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Content)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Packet) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD06268a7EncodeECCommon(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Packet) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD06268a7EncodeECCommon(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Packet) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD06268a7DecodeECCommon(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Packet) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD06268a7DecodeECCommon(l, v)
}
